config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users, controllers: {registrations: 'users/registrations'}
  
  devise_scope :user do
    #resources :users, :only => [:show, :index] 
    #get "users_index", :to => "users/registrations#index" 
    get 'registration/index', :to => 'users/registrations#index'
    
  end

  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :medical_shops do
  	get 'medical_shop_verification', to: "medical_shop_verification"
  	collection do
    	get 'search'
  	end
  end

  resources :users do 
  	get 'block_unblock_user', :to => 'users#block_unblock_user'
  end
  #get 'users/registrations/:id' => 'users/registrations#show'
end

app/models/medical_shop.rb
class MedicalShop < ApplicationRecord
	validates :name, :mobile_number, :opening_time, :closing_time, :registration_number, :registerd_person_name, :discount, :shop_address, :area, :city, :state, :pincode, presence: true
  has_one_attached :image
  belongs_to :user
  after_validation :geocode 
	geocoded_by :pincode

	scope :verified,-> { where(verify: true) }
	scope :not_verified,-> { where(verify: false) }
end

app/controllers/medical_shops_controller.rb
class MedicalShopsController < ApplicationController
  before_action :set_medical_shop, only: [:show, :edit, :update]
  before_action :set_medical_shops, only: [:index, :medical_shop_verification]

	load_and_authorize_resource

	def new
		@medical_shop = MedicalShop.new
	end

	def create
		@medical_shop = MedicalShop.new(medical_shop_params)
    @medical_shop.image.attach(params[:medical_shop ][:image])
		return redirect_to root_path if @medical_shop.save
		flash[:alert] = @medical_shop.errors.full_messages.join(', ')
    render 'new'
	end

	def show
  end

  def edit 
    return redirect_to root_path unless @medical_shop.user_id == current_user.id or current_user.has_role? :admin
  end
  
  def update
    #debugger
    return redirect_to root_path unless @medical_shop.user_id == current_user.id or current_user.has_role? :admin
    if @medical_shop.update(medical_shop_params)
      flash[:notice] = "Medical Shop updated."
      redirect_to medical_shop_path(@medical_shop)
    else
      flash[:alert] = @medical_shop.errors.full_messages.join(', ')
      render :edit
    end
  end

  def index
  end

  def search
    if params[:search].blank? and params[:discount_min].blank? and 
      params[:discount_max].blank? and params[:open].blank? and params[:search_form].present?
      redirect_to(root_path, alert: "Empty field!") 
    else 
      if current_user.present? and current_user.has_role? :admin
        @medical_shopss = MedicalShop.all
        @medical_shopss = @medical_shopss.where(" ? BETWEEN opening_time AND closing_time ", Time.now.strftime("%H"))  if params[:open].present?
        @medical_shopss = @medical_shopss.where("discount >= ?", params[:discount_min])  if params[:discount_min].present?
        @medical_shopss = @medical_shopss.where("discount <= ?", params[:discount_max])  if params[:discount_max].present?
        @medical_shopss = @medical_shopss.where("lower(city) LIKE ? OR lower(name) LIKE ? OR 
           lower(area) LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%",
            "%#{params[:search]}%") if params[:search].present?
      else  
        @medical_shopss = MedicalShop.all
        @medical_shopss = @medical_shopss.verified unless current_user.present? and current_user.has_role? :admin
        @medical_shopss = @medical_shopss.near([current_user.address.latitude, current_user.address.latitude], 50, :order => :distance) if current_user.present?
        @medical_shopss = @medical_shopss.where(" ? BETWEEN opening_time AND closing_time ", Time.now.strftime("%H"))  if params[:open].present?
        @medical_shopss = @medical_shopss.where("discount >= ?", params[:discount_min])  if params[:discount_min].present?
        @medical_shopss = @medical_shopss.where("discount <= ?", params[:discount_max])  if params[:discount_max].present?
        @medical_shopss = @medical_shopss.where("lower(city) LIKE ? OR lower(name) LIKE ? OR 
           lower(area) LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%",
            "%#{params[:search]}%") if params[:search].present?
        @medical_shopss = MedicalShop.near(params[:my_location], 5, :order => :distance) unless current_user.present? and params[:my_location].blank?
      end
    end 
  end

  def medical_shop_verification
  	@medical_shop = MedicalShop.find(params[:medical_shop_id])
  	@medical_shop.verify = !@medical_shop.verify
  	@medical_shop.save
  	redirect_to medical_shops_path
  end
  

  private

  def set_medical_shop
    @medical_shop = MedicalShop.find(params[:id])
  end

  def set_medical_shops
    @medical_shops = MedicalShop.all
    @medical_shops = @medical_shops.verified unless current_user.present? and current_user.has_role? :admin
  end

  def medical_shop_params
    params.require(:medical_shop).permit( :user_id, :image, :latitude, :longitude, :name, :mobile_number, :opening_time, :closing_time, :registration_number, :registerd_person_name, :verify, :discount, :shop_address, :area, :city, :state, :pincode)
  end
end

app/helpers/medical_shops_helper.rb
module MedicalShopsHelper
end

app/views/medical_shops/edit.html.erb
 <div class="container">
<center>
  <div id="formContent">
    <center>
<h4> edit medical store</h4>

<%= form_for :medical_shop, html: { method: :put }, :url => { :action => "update" } do |f| %>

  <table>
    <tr><td><hr></td></tr>
    <tr>
      <td><h5>Basic Information :</h5></td>
    </tr>
    <tr><td><hr></td></tr>  
    <tr>
      <td><%= f.text_field :name, placeholder: "medical_name" %></td>
    </tr>
    <tr><td><hr></td></tr>
    <tr>  
      <td><%= f.text_field :registerd_person_name, placeholder: "registerd_person_name" %></td>
    </tr>
    <tr><td><hr></td></tr>  
    <tr>
      <td><%= f.text_field :mobile_number, placeholder: "mobile_number" %></td>
    </tr>  
    <tr><td><hr></td></tr>
        <%= f.hidden_field :verify %>
        <%= f.hidden_field :user_id, value: current_user.id %>
    <tr>  
      <td><%= f.text_field :registration_number,  placeholder: "registration_number" %></td>
    </tr>   
    <tr><td><hr></td></tr>
    <tr><td>Insert_Licence</td></tr>
    
    <tr>  
      <td> <%= f.file_field :image, direct_upload: true %></td>
    </tr>   
    <tr><td><hr></td></tr>
         

    <tr>
      <td><%= f.text_field :opening_time,  placeholder: "opening_time" %></td>
    </tr> 

    <tr><td><hr></td></tr>

    <tr>
      <td><%= f.text_field :closing_time,  placeholder: "closing_time" %></td>
    </tr> 

    <tr><td><hr></td></tr>

    <tr>  
      <td><%= f.text_field :discount,  placeholder: "discount" %></td>
    </tr> 

    <tr><td><hr></td></tr>

    <tr>  
      <td><%= f.text_area :shop_address,  placeholder: "shop_addres" %></td>
    </tr> 

    <tr><td><hr></td></tr>
    
    <tr>  
      <td><%= f.text_field :area,  placeholder: "area" %></td>
    </tr> 

    <tr><td><hr></td></tr>
    
    <tr>  
      <td><%= f.text_field :city,  placeholder: "city" %></td>
    </tr> 

    <tr><td><hr></td></tr>
    
    <tr>  
      <td><%= f.text_field :state,  placeholder: "state" %></td>
    </tr> 

    <tr><td><hr></td></tr>
    
    <tr>  
      <td><%= f.text_field :pincode,  placeholder: "pincode" %></td>
    </tr> 
    <%= f.hidden_field :latitude, :value => params[:latitude] %>
          <%= f.hidden_field :longitude, :value => params[:longitude] %>
    <tr><td><hr></td></tr>

  </table>
  <%= f.submit "Update", class:"btn btn-outline-info" %>
<% end %>
</center>
</div>
</center>
<%#= render "devise/shared/links" %>
</div>

app/views/medical_shops/index.html.erb
<div class="container">
<table class="table">
	<tr class="bg-secondary">
	  	<th>Medical_Shop_Name:</th>
	  	<th>Mobile_number:</th>
	  	<th>Address</th>
	  	<th>latitude:</th>	
	  <% if can? :manage, :all %>
	  	<th>verify:</th>
	  <% end %>	
	  	<th>More:</th>
	  <% if can? :edit, MedicalShop %>
	  	<th>Edit:</th>
	  <% end %>
      <!-- <td>Image:</td> -->
	  </tr>
		<% @medical_shops.each do |medical_shop| %>
	
		  <tr>  
		  	<td><%= medical_shop.name %></td>
		  	<td><%= medical_shop.mobile_number %></td>
		  	<td><%= medical_shop.area %>, <%= medical_shop.city %></td>
		  	<td><%= medical_shop.latitude %></td>
		  	<% if can? :manage, :all %>
			  	<td>
			  	
			  		<% if medical_shop.verify == false %> 
			  			<%= link_to "Not Verify", medical_shop_medical_shop_verification_path(medical_shop.id), data: {confirm: "Are you sure?"} %>
			  		<% else %>
			  			<%= link_to " Verified", medical_shop_medical_shop_verification_path(medical_shop.id), data: {confirm: "Are you sure?"} %>
			  		<% end %>
			  		
			    </td>
			  <% end %>
		    <td><%= link_to "More", medical_shop_path(medical_shop.id) %></td>
		    <% if can? :edit, MedicalShop %>
		    	<td><%= link_to "edit", edit_medical_shop_path(medical_shop.id) %></td>
		    <% end %>
	      <!-- <td><%#= image_tag medical_shop.image %></td> -->
		  </tr>
	  <% end %>
</table>
</div>

app/views/medical_shops/new.html.erb
<div class="container">
<center>
  <div id="formContent">
    <center>
<h4>Sign up for medical store</h4>

<%= form_for :medical_shop, :url => { :action => "create" } do |f| %>

  <table>
    <tr><td><hr></td></tr>
    <tr>
      <td><h5>Basic Information :</h5></td>
    </tr>
    <tr><td><hr></td></tr>  
    <tr>
      <td><%= f.text_field :name, placeholder: "medical_name" %></td>
    </tr>
    <tr><td><hr></td></tr>
    <tr>  
      <td><%= f.text_field :registerd_person_name, placeholder: "registerd_person_name" %></td>
    </tr>
    <tr><td><hr></td></tr>  
    <tr>
      <td><%= f.text_field :mobile_number, placeholder: "mobile_number" %></td>
    </tr>  
    <tr><td><hr></td></tr>
        <%= f.hidden_field :verify %>
        <%= f.hidden_field :user_id, value: current_user.id %>
    <tr>  
      <td><%= f.text_field :registration_number,  placeholder: "registration_number" %></td>
    </tr>   
    <tr><td><hr></td></tr>
    <tr><td>Insert_Licence</td></tr>
    
    <tr>  
      <td> <%= f.file_field :image, direct_upload: true, accept: 'image/jpeg' %></td>
    <!-- accept: 'application/pdf, 
    application/zip,application/vnd.openxmlformats-officedocument.wordprocessingml.document' -->
    </tr>   
    <tr><td><hr></td></tr>
         

    <tr>
      <td><%= f.text_field :opening_time,  placeholder: "opening_time" %></td>
    </tr> 

    <tr><td><hr></td></tr>

    <tr>
      <td><%= f.text_field :closing_time,  placeholder: "closing_time" %></td>
    </tr> 

    <tr><td><hr></td></tr>

    <tr>  
      <td><%= f.text_field :discount,  placeholder: "discount" %></td>
    </tr> 

    <tr><td><hr></td></tr>

    <tr>  
      <td><%= f.text_area :shop_address,  placeholder: "shop_addres" %></td>
    </tr> 

    <tr><td><hr></td></tr>
    
    <tr>  
      <td><%= f.text_field :area,  placeholder: "area" %></td>
    </tr> 

    <tr><td><hr></td></tr>
    
    <tr>  
      <td><%= f.text_field :city,  placeholder: "city" %></td>
    </tr> 

    <tr><td><hr></td></tr>
    
    <tr>  
      <td><%= f.text_field :state,  placeholder: "state" %></td>
    </tr> 

    <tr><td><hr></td></tr>
    
    <tr>  
      <td><%= f.text_field :pincode,  placeholder: "pincode" %></td>
    </tr> 
    <%= f.hidden_field :latitude, :value => params[:latitude] %>
          <%= f.hidden_field :longitude, :value => params[:longitude] %>
    <tr><td><hr></td></tr>

  </table>
  <%= f.submit "Sign up", class:"btn btn-outline-info" %>
<% end %>
</center>
</div>
</center>
<%#= render "devise/shared/links" %>
</div>

app/views/medical_shops/search.html.erb
<div class="container p-4">
	<center><h4>Medical Shop</h4></center>
	<div class="col-md-12 mt-4">
		<%= form_tag(search_medical_shops_path, :method => :get, class: "navbar-form navbar-left") do %>
		<div class="row">
			<div class="form-group mr-3">
	  		<%= text_field_tag :search, params[:search], placeholder: "city / area / shop_name", class: "form-control" %>
			</div>
			<div class="form-group mr-3">
	  		<%= text_field_tag :discount_min, params[:discount_min], placeholder: "Discount Min", class: "form-control" %>
			</div>
			<div class="form-group mr-3">
	  		<%= text_field_tag :discount_max, params[:discount_max], placeholder: "Discount Max", class: "form-control" %>
			</div>
      
      <% unless current_user.present? %>
				<div class="form-group mr-3">
	  			<%= text_field_tag :my_location, params[:my_location], placeholder: "near area better if pincode", class: "form-control" %>
				</div>
			<% end %>

			<div class="form-group mr-3">
				<%= check_box_tag :open, Time.now.strftime("%H") %> open
    	</div>
    	
    	<%= hidden_field_tag :search_form, :value => "search_form"  %>
			<div class="form-group">
	  		<%= submit_tag ("Search"), class: "btn btn-primary" %>
	  	</div>
		</div>
	  
	<% end %>
	</div>


	<table class="table bg-dark text-light" >
		<% @medical_shopss.each_with_index do |result, i| %>
		<tr><td colspan="2"><span class="badge badge-light"><%= i+1 %></span></td></tr>
		<tr><th>Shop Name</th><td><%= result.name %></td></tr>
  	<tr><th>Contact Number</th><td><%= result.mobile_number %></td></tr>
  	<tr><th>registerd_person_name</th><td><%= result.registerd_person_name %></td></tr>
  	<tr><th>registration_number</th><td><%= result.registration_number %></td></tr>
  	<tr><th>discount</th><td><%= result.discount %>%</td></tr>
  	<tr><th>opening_time</th><td><%= result.opening_time %> </td></tr>
  	<tr><th>closing_time</th><td><%= result.closing_time %></td></tr>
  	<tr><th>shop_address</th><td><%= result.shop_address %>, <%= result.area %>,  <%= result.city %>,<%= result.state %> pincode( <%= result.pincode %> )</td></tr>
  	
  	<tr><th>Liecence</th><td><%= image_tag result.image %></td></tr>
  	<tr><td colspan="2" style="background-color: #e5e4ff;"></td></tr>
    <% end %>
  </table>
</div>

app/views/medical_shops/show.html.erb
<div class="container">
	<center>medical shop</center>
	<table class="table bg-dark text-light" >
		<tr><th>Shop Name</th><td><%= @medical_shop.name %></td></tr>
  	<tr><th>Contact Number</th><td><%= @medical_shop.mobile_number %></td></tr>
  	<tr><th>registerd_person_name</th><td><%= @medical_shop.registerd_person_name %></td></tr>
  	<tr><th>registration_number</th><td><%= @medical_shop.registration_number %></td></tr>
  	<tr><th>discount</th><td><%= @medical_shop.discount %>%</td></tr>
  	<tr><th>opening_time</th><td><%= @medical_shop.opening_time %> </td></tr>
  	<tr><th>closing_time</th><td><%= @medical_shop.closing_time %></td></tr>
  	<tr><th>shop_address</th><td><%= @medical_shop.shop_address %>, <%= @medical_shop.area %>,  <%= @medical_shop.city %>,<%= @medical_shop.state %> pincode( <%= @medical_shop.pincode %> )</td></tr>
  	
  	<tr><th>Liecence</th><td><%= image_tag @medical_shop.image %></td></tr>
  </table>
</div>