config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users, controllers: {registrations: 'users/registrations'}
  
  devise_scope :user do
    #resources :users, :only => [:show, :index] 
    #get "users_index", :to => "users/registrations#index" 
    get 'registration/index', :to => 'users/registrations#index'
    
  end

  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :medical_shops do
  	get 'medical_shop_verification', to: "medical_shop_verification"
  	collection do
    	get 'search'
  	end
  end

  resources :users do 
  	get 'block_unblock_user', :to => 'users#block_unblock_user'
  end
  #get 'users/registrations/:id' => 'users/registrations#show'
end

app/views/layouts/_footer.html.erb
<center><p class="bg-secondary">&copy m0n!k@ Verm@</p></center>

app/views/layouts/_header.html.erb
<div class="header">
<center>
	<%= link_to 'search', search_medical_shops_path, class:"bg-dark text-warning" %>
  <%= link_to "All Medical", medical_shops_path , class:"bg-dark text-warning"%>  
  <% if user_signed_in? %>
  |	<%= link_to 'logout', destroy_user_session_path, method: :delete, class:"bg-dark text-warning" %> | <%= link_to 'edit', edit_user_registration_path, class:"bg-dark text-warning"%> |   <%= link_to "users", users_path , class:"bg-dark text-warning"%> | 
  <% else %>
  	| <%= link_to 'Sign In', new_user_session_path, class:"bg-dark text-warning"%> /
  	<%= link_to "Sign Up for user", new_user_registration_path(:role => 'customer'), class:"bg-dark text-warning" %> | <%= link_to "Sign Up for medical", new_user_registration_path(:role => 'shopkeeper'), class:"bg-dark text-warning" %> |<%#= link_to "Forgot your password?", new_password_path(resource_name) %> 
  <% end %>
</center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmergencyMedical</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render "layouts/header"%>

  </head>

  <body>
    <% if notice.present? %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong><%= notice %></strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong><%= alert %></strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>

  </body>
  <%= render "layouts/footer"%>
</html>